"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { type Lang, LANG_COOKIE, LANG_OPTIONS, LANG_NAMES, dirForLang } from "./i18n";

export { type Lang, LANG_COOKIE, LANG_OPTIONS, LANG_NAMES, dirForLang };

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
}

// Arabic is the source locale: content keys (Arabic strings) fall back to
// themselves when no translation exists, so lookups are safe for data.
const ar: Record<string, string> = {
  // ---- Navigation ----
  home: "الرئيسية",
  "nav.years": "السنوات الدراسية",
  "nav.resources": "الموارد",
  "nav.search": "ابحث...",
  "nav.searchPh": "ابحث عن ملخصات، تمارين، دروس...",
  "nav.searchAria": "بحث",
  "nav.soundOn": "كتم الأصوات",
  "nav.soundOff": "تشغيل الأصوات",
  "nav.soundEnabled": "الأصوات مفعّلة",
  "nav.soundMuted": "الأصوات مكتومة",
  "nav.themeDay": "الوضع النهاري",
  "nav.themeNight": "الوضع الليلي",
  "nav.changeLang": "تغيير اللغة",
  "nav.menu": "القائمة",
  "nav.quickSearch": "ابحث سريعًا ( / )",
  grade1: "السنة الأولى ثانوي",
  grade2: "السنة الثانية ثانوي",
  grade3: "السنة الثالثة ثانوي",
  grade4: "السنة الرابعة متوسط",
  g1: "1 ثانوي",
  g2: "2 ثانوي",
  g3: "3 ثانوي",
  g4: "4 متوسط",
  distributions: "التوزيعات",
  videosNav: "الفيديوهات",
  teacherBag: "حقيبة الأستاذ",
  courses: "الدورات التعليمية",
  apps: "التطبيقات والبرامج",
  about: "من نحن؟",
  follow: "تابعونا",
  admin: "لوحة التحكم",
  bookmarks: "المفضلة",
  faq: "الأسئلة الشائعة",
  contact: "اتصل بنا",

  // ---- Common ----
  "common.all": "الكل",
  "common.view": "مشاهدة",
  "common.download": "تحميل",
  "common.back": "رجوع",
  "common.explore": "استكشف",
  "common.loading": "جارٍ التحميل...",
  "common.price": "دج",
  "common.free": "مجاني",
  "common.locked": "مقفول",
  "common.freeCta": "ابدأ مجانًا",
  "common.crumbHome": "الرئيسية",
  "common.new": "جديد",

  // ---- Hero ----
  "hero.badge": "شعارنا @profpica — تتفكرها مع بيكا",
  "hero.title1": "منصة الأستاذ بيكا",
  "hero.title2": "لتعليم الفيزياء",
  "hero.title3": "كل ما يحتاجه الطالب",
  "hero.desc": "ملخصات، تمارين محلولة، فروض واختبارات، دورات تعليمية، تطبيقات ذكية، وآخر الفيديوهات التعليمية — كل شيء في مكان واحد.",
  "hero.watch": "من نحن؟",
  "hero.courses": "استكشف الدورات",
  "hero.videoTitle": "شاهد أحدث الدروس على يوتيوب",
  "hero.videoSub": "@ProfPica — شروحات كاملة وحلول تمارين",
  "hero.videoTitleAttr": "فيديو تعريفي - DzPhy",
  "hero.posterAlt": "الأستاذ بيكا - دروس الفيزياء",
  "hero.watchAria": "شاهد الدروس على قناة يوتيوب",

  // ---- Start Here ----
  "sh.title": "ابدأ من هنا",
  "sh.subtitle": "خمس خطوات بسيطة تعرّفك على كل ما تحتاجه",
  "sh.close": "إخفاء دليل البداية",
  "sh.1title": "اختر سنتك",
  "sh.1desc": "ابدأ من مستواك الدراسي",
  "sh.2title": "شاهد الدروس",
  "sh.2desc": "فيديوهات وقوائم مرتّبة",
  "sh.3title": "حمّل الملفات",
  "sh.3desc": "توزيعات وملخصات PDF",
  "sh.4title": "تابع الملخصات",
  "sh.4desc": "صور ومفاهيم سريعة",
  "sh.5title": "آخر المستجدات",
  "sh.5desc": "أخبار وإعلانات مهمة",

  // ---- Grade cards ----
  "gc.badge": "المستويات الدراسية",
  "gc.t1": "اختر",
  "gc.t2": "مستواك",
  "gc.desc": "محتوى مرتّب لكل مستوى وفق المنهاج الجزائري — لكل مستوى لونه الخاص",
  "gc.explore": "استكشف القسم",
  "chip.resumes": "ملخصات",
  "chip.exercises": "تمارين",
  "chip.devoirs": "فروض",
  "chip.tp": "عملي",
  "chip.videos": "فيديو",
  "chip.lessons": "دروس",
  "chip.skills": "مكتسبات",
  "chip.distribution": "توزيع",

  // ---- Subjects (content keys) ----
  الميكانيكا: "الميكانيكا",
  الكهرباء: "الكهرباء",
  الكيمياء: "الكيمياء",
  البصريات: "البصريات",
  النووي: "النووي",
  الفيزياء: "الفيزياء",
  "ميكانيكا/بصريات": "ميكانيكا/بصريات",
  "جميع الوحدات": "جميع الوحدات",

  // ---- Level descriptions (content keys) ----
  "أسس الفيزياء والكيمياء — الميكانيكا، الكهرباء والمادة.": "أسس الفيزياء والكيمياء — الميكانيكا، الكهرباء والمادة.",
  "قوانين نيوتن، الطاقة، الدوائر الكهربائية والتفاعلات.": "قوانين نيوتن، الطاقة، الدوائر الكهربائية والتفاعلات.",
  "الإعداد للباكالوريا — الموجات، الميكانيكا والكيمياء المتقدمة.": "الإعداد للباكالوريا — الموجات، الميكانيكا والكيمياء المتقدمة.",
  "التحضير لشهادة التعليم المتوسط — الوحدات، القياس والتحويلات.": "التحضير لشهادة التعليم المتوسط — الوحدات، القياس والتحويلات.",
  "قوانين نيوتن": "قوانين نيوتن",
  "الطاقة": "الطاقة",
  "الموجات": "الموجات",
  "الباكالوريا": "الباكالوريا",
  "المادة": "المادة",
  "القياس والتحويلات": "القياس والتحويلات",
  "الوحدات": "الوحدات",

  // ---- Platform guide ----
  "pg.badge": "دليل الطالب الجديد",
  "pg.t1": "ماذا تجد في",
  "pg.t2": "كل منصة؟",
  "pg.desc": "كل منصة لها وظيفة واحدة واضحة — اعرف أين تذهب وماذا ستجد في كل مكان.",
  "pg.open": "فتح المنصة",
  "youtube.tagline": "الدروس المفصّلة",
  "youtube.desc": "الدروس الكاملة، البثوث المباشرة، حل السلاسل والمراجعات الشاملة لكل مستوى.",
  "tiktok.tagline": "أفكار سريعة",
  "tiktok.desc": "أفكار فيزياء سريعة، تبسيط مفهوم، أو حيلة ذكية في ثوانٍ معدودة.",
  "telegram.tagline": "حقيبة الملفات",
  "telegram.desc": "ملفات الأستاذ: PDF، سلاسل تمارين، ملخصات ومواضيع قابلة للتحميل مباشرة.",
  "instagram.tagline": "صور وملخصات",
  "instagram.desc": "صور وملخصات بصرية، قوانين ومفاهيم أساسية تُثبّت المعلومة بسرعة.",
  "facebook.tagline": "المستجدات الرسمية",
  "facebook.desc": "المنشورات المهمة، الأخبار الوزارية والتنبيهات الرسمية والملخصات الشاملة.",

  // ---- Videos section ----
  "vs.badge": "الفيديوهات التعليمية",
  "vs.t1": "تعلم بالفيديو",
  "vs.t2": "مجانا",
  "vs.desc": "دروس مرتبة في قوائم تشغيل حسب المستوى — تُحدَّث تلقائيًا من قناة يوتيوب.",
  "vs.all": "كل الفيديوهات",
  "vs.yt": "قوائم تشغيل YouTube -",
  "vs.error": "تعذّر تحميل الفيديوهات، جرّب فتح صفحة الفيديوهات مباشرة.",
  "vs.errorLink": "الانتقال إلى قوائم التشغيل",
  "vs.videosCount": "فيديو",
  "vs.playlist": "قائمة تشغيل",
  "vs.browseAll": "استعرض قوائم التشغيل كاملة",
  "vs.tiktok": "آخر فيديوهات TikTok -",
  "vs.tiktokMore": "مشاهدة المزيد على TikTok",
  "sg.tiktokTitle": "أهم فيديوهات التيك توك",
  "sg.tiktokSub": "أفكار سريعة ومقاطع مختارة من @profpica",
  "sg.igTitle": "أحدث منشورات إنستغرام",
  "sg.igSub": "آخر ريلز ومنشورات من @prof_pica",

  // ---- Home social ----
  "hs.badge": "المنصات التعليمية",
  "hs.t1": "الصور، الملفات",
  "hs.t2": "والمستجدات",
  "hs.instagram": "إنستغرام — صور وملخصات",
  "hs.instagramSub": "قوانين ومفاهيم بصرية سريعة من @prof_pica",
  "hs.follow": "متابعة",
  "hs.telegram": "تلغرام — حقيبة الملفات",
  "hs.telegramSub": "PDF، سلاسل تمارين، ملخصات ومواضيع",
  "hs.tg1": "ملفات PDF جاهزة للتحميل",
  "hs.tg2": "سلاسل تمارين ومواضيع",
  "hs.tg3": "إعلانات وتحديثات مهمة",
  "hs.tgCta": "انضم إلى قنوات التلغرام",
  "hs.facebook": "فيسبوك — المستجدات الرسمية",
  "hs.facebookSub": "أخبار وزارية، تنبيهات وملخصات شاملة",
  "hs.fbOfficial": "الصفحة الرسمية",
  "hs.fbOfficialSub": "المنشورات والمستجدات اليومية والملخصات",
  "hs.fbPersonal": "حساب الأستاذ الشخصي",
  "hs.fbPersonalSub": "تواصل مباشر وتفاعل مع الأستاذ بيكا",
  "hs.all": "كل المنصات والمجتمعات",

  // ---- Latest content ----
  "lc.badge": "أحدث الإضافات",
  "lc.t1": "آخر ما تم",
  "lc.t2": "إضافته",
  "lc.all": "عرض الكل",
  "lc.watch": "مشاهدة",
  "lc.pdf": "تحميل PDF",
  "السنة الأولى": "السنة الأولى",
  "السنة الثانية": "السنة الثانية",
  "السنة الثالثة": "السنة الثالثة",
  "ملخص": "ملخص",
  "تمارين": "تمارين",
  "فرض": "فرض",
  "عمل تطبيقي": "عمل تطبيقي",
  "فيديو": "فيديو",

  // ---- Courses ----
  "cs.badge": "الدورات التعليمية",
  "cs.t1": "دورات",
  "cs.t2": "مميزة",
  "cs.t3": "للفيزياء",
  "cs.all": "كل الدورات",
  "cs.free": "دورات مجانية",
  "cs.paid": "دورات مدفوعة",
  "cs.watch": "مشاهدة الدورة",
  "cs.lessons": "درس",
  "cs.modalTitle": "تواصل مع الأستاذ",
  "cs.modalDesc": "لمزيد من المعلومات وإعطائك رابط الدخول إلى الدورة المدفوعة، يرجى التواصل مع الأستاذ بيكا مباشرة.",
  "cs.modalCta": "تواصل مع الأستاذ",
  "cs.modalClose": "إغلاق",

  // ---- Apps ----
  "as.badge": "التطبيقات والبرامج",
  "as.t1": "اكتشف أدوات",
  "as.t2": "منصة الأستاذ بيكا",
  "as.t3": "الذكية",
  "as.desc": "تطبيقات ذكية مصممة خصيصا لمساعدة الطالب الجزائري على فهم الفيزياء بطريقة تفاعلية",
  "as.try": "تجربة التطبيق",
  "apps.heroTitle": "التطبيقات والبرامج",
  "apps.heroDesc": "أدوات منصة الأستاذ بيكا الذكية — محاكيات تفاعلية وحاسبات فيزيائية",

  // ---- Why DzPhy ----
  "wd.badge": "لماذا منصة الأستاذ بيكا للفيزياء؟",
  "wd.t1": "ما يجعل",
  "wd.t2": "منصة الأستاذ بيكا",
  "wd.t3": "مختلفة",
  "wd.desc": "لسنا مجرد موقع تعليمي - نحن منظومة متكاملة لتعلم الفيزياء بالطريقة الصحيحة",
  "wd1.title": "محتوى منظم",
  "wd1.desc": "محتوى مرتب بشكل منهجي يتبع المنهاج الدراسي الجزائري خطوة بخطوة",
  "wd2.title": "منهاج جزائري 100%",
  "wd2.desc": "مصمم خصيصا للطالب الجزائري ويوافق البرامج الرسمية لوزارة التربية",
  "wd3.title": "شرح مبسط",
  "wd3.desc": "أسلوب شرح سهل ومبسط يجعل أصعب مفاهيم الفيزياء واضحة وقابلة للفهم",
  "wd4.title": "تحديثات مستمرة",
  "wd4.desc": "محتوى جديد يضاف باستمرار يواكب التغييرات في المنهاج والامتحانات",
  "wd5.title": "أدوات ذكية",
  "wd5.desc": "تطبيقات ومحاكيات تفاعلية تجعل تعلم الفيزياء تجربة ممتعة ومثيرة",
  "wd6.title": "مجتمع تعليمي",
  "wd6.desc": "مجتمع من الطلاب والأساتذة يتشاركون المعرفة ويدعمون بعضهم البعض",

  // ---- About section ----
  "ab.badge": "✍️ الأستاذ بيكا 🎓",
  "ab.t1": "من هو",
  "ab.t2": "الأستاذ بيكا؟",
  "ab.zoom": "اضغط على الصورة لتكبيرها وقراءة السيرة بوضوح",
  "ab.edu": "خريج المدرسة العليا للأساتذة",
  "ab.tagline": "أبسّط الفيزياء بطريقة سهلة وممتعة 💡",
  "ab.item1": "📝 ملخصات منظمة وشاملة",
  "ab.item2": "📚 حلول تمارين محلولة خطوة بخطوة",
  "ab.item3": "💡 أفكارٌ لن تجدها في الكتب",
  "ab.follow": "🔗👇 تابعونا عبر الروابط",
  "ab.mission": "رسالتنا",
  "ab.missionDesc": "جعل تعلم الفيزياء تجربة ممتعة وميسرة لكل طالب جزائري، من خلال توفير أفضل المحتويات التعليمية والأدوات الذكية المجانية.",

  // ---- Newsletter ----
  "newsletter.title": "ابقَ على اطلاع",
  "newsletter.desc": "اشترك في النشرة البريدية لتصلك أحدث الدروس والملخصات والتمارين مباشرة إلى بريدك",
  "newsletter.placeholder": "أدخل بريدك الإلكتروني",
  "newsletter.subscribe": "اشترك الآن",
  "newsletter.success": "تم الاشتراك!",
  "newsletter.privacy": "نحترم خصوصيتك - لن نشارك بريدك مع أي طرف ثالث",

  "ab.heroTitle": "من نحن؟",
  "ab.heroDesc": "تعرف على الأستاذ بيكا ومنصة الأستاذ بيكا للفيزياء",
  "ab.cvAlt": "السيرة الذاتية - الأستاذ بيكا",

  // ---- Teacher page ----
  "teacher.title": "حقيبة الأستاذ",
  "teacher.desc": "موارد تعليمية متكاملة لأساتذة الفيزياء",
  "teacher.r1title": "خطط الدروس",
  "teacher.r1desc": "خطط دروس جاهزة وفق المنهاج الرسمي الجزائري",
  "teacher.r2title": "نماذج الفروض",
  "teacher.r2desc": "نماذج فروض جاهزة قابلة للتعديل والطباعة",
  "teacher.r3title": "اختبارات التقييم",
  "teacher.r3desc": "اختبارات متنوعة لتقييم مستوى الطلاب",
  "teacher.telegram": "📱 تواصل مع الأستاذ عبر تلغرام",
  "teacher.telegramDesc": "انضم إلى قناة التلغرام للحصول على آخر التحديثات والملفات والتمارين",
  "teacher.join": "انضم إلى القناة",

  // ---- Distributions page ----
  "dp.title": "التوزيعات السنوية",
  "dp.desc": "التوزيعات السنوية الرسمية لمادة العلوم الفيزيائية لكل مستويات الطور الثانوي وشهادة التعليم المتوسط — حمّلها مباشرة بصيغة PDF.",
  "dp.searchPh": "ابحث عن توزيع، مستوى، شعبة...",
  "dp.level": "المستوى",
  "dp.stream": "الشعبة",
  "dp.category": "التصنيف",
  "dp.showing": "عرض",
  "dp.files": "ملف",
  "dp.empty": "لا توجد ملفات مطابقة",
  "dp.emptyHint": "جرّب تعديل الفلاتر أو كلمات البحث",
  "dp.download": "تحميل مباشر (PDF)",
  "dp.soon": "قريبًا",

  // ---- Videos page ----
  "vp.badge": "الفيديوهات التعليمية",
  "vp.title": "قوائم التشغيل",
  "vp.desc": "جميع دروس ومكتسبات مادة العلوم الفيزيائية مرتبة في قوائم تشغيل حسب المستوى — يُحدَّث المحتوى تلقائيًا عند إضافة أي فيديو جديد على قناة يوتيوب.",
  "vp.loading": "جارٍ جلب أحدث الفيديوهات من يوتيوب...",
  "vp.errorTitle": "تعذّر الاتصال بقوائم التشغيل",
  "vp.errorHint": "تأكد من اتصال الإنترنت ثم أعد المحاولة",
  "vp.emptyTitle": "لا توجد قوائم في هذا المستوى بعد",
  "vp.emptyHint": "جرّب مستوى آخر أو تصفّح كل القوائم.",
  "vp.all": "كل القوائم",
  "vp.openFull": "فتح القائمة الكاملة على يوتيوب",
  "vp.watchAll": "شاهد كل فيديوهات هذه القائمة على يوتيوب",
  "أفكار ودورات": "أفكار ودورات",

  // ---- Search page ----
  "sp.title": "ابحث في منصة الأستاذ بيكا للفيزياء",
  "sp.desc": "دروس، ملخصات، تمارين، فروض، فيديوهات، دورات وتوزيعات — كل المحتوى في مكان واحد",
  "sp.aria": "ابحث في المنصة",
  "sp.placeholder": "اكتب: نيوتن، الكهرباء، القذائف، BAC...",
  "sp.empty": "ابدأ بكتابة ما تبحث عنه",
  "sp.emptySub": "ملخصات، تمارين، فروض، فيديوهات، دورات...",
  "sp.noResults": "لا توجد نتائج لـ",
  "sp.noResultsHint": "جرّب كلمة أخرى مثل: نيوتن، الكهرباء، BEM",
  "sp.for": "نتيجة لـ",
  "sp.kbd": "— استخدم ↑ ↓ ثم Enter",
  "مستوى دراسي": "مستوى دراسي",
  "دورة": "دورة",
  "توزيع سنوي": "توزيع سنوي",
  "تطبيق": "تطبيق",
  "صفحة": "صفحة",
  "فيديوهات": "فيديوهات",

  // ---- Follow page ----
  "fp.title": "تابعونا",
  "fp.desc": "كل منصات الأستاذ بيكا في مكان واحد — ابق على اطلاع بأحدث الدروس والملفات والتحديثات اليومية.",
  "fp.linktree": "الرابط الشامل — linktr.ee/profpica",
  "fp.official": "المنصات الرسمية",
  "fp.officialSub": "قنوات المتابعة اليومية للأستاذ بيكا",
  "fp.communities": "المجتمعات المنظمة",
  "fp.communitiesSub": "مجلدات القنوات ومجتمعات النقاش — ملفات وروح فريق واحد",
  "fp.groups": "مجموعات التواصل حسب مستواك",
  "fp.groupsSub": "دردشات مباشرة على إنستغرام وماسنجر حسب القسم الدراسي",
  "fp.support": "دعم المحتوى والدفع السريع ⚡",
  "fp.supportSub": "ساهم في استمرار المحتوى التعليمي المجاني",
  "fp.copied": "تم النسخ",
  "fp.copy": "نسخ",

  // ---- Grade page ----
  "gd.distBanner": "التوزيع السنوي —",
  "gd.distDesc": "حمّل التوزيع السنوي الرسمي لمادة العلوم الفيزيائية بصيغة PDF مباشرة.",
  "gd.download": "تحميل",
  "gd.chooseStream": "اختر الشعبة",
  "gd.chooseStreamSub": "اختر شعبتك للوصول إلى المحتوى المخصص",
  "gd.sciStreams": "الشعب العلمية",
  "gd.litStreams": "الشعب الأدبية",
  "gd.choose": "اختر",
  "gd.back": "الرجوع للشعب",
  "gd.contentSci": "المحتوى الدراسي - شعبة علمية",
  "gd.contentLit": "المحتوى الدراسي - شعبة أدبية",
  "gd.chooseSection": "اختر القسم الذي تريد تصفحه",
  "gd.bemTitle": "محتوى شهادة التعليم المتوسط",
  "gd.explore": "استكشف",
  "الشعب العلمية": "الشعب العلمية",
  "الشعب الأدبية": "الشعب الأدبية",
  "علوم تجريبية": "علوم تجريبية",
  "تقني رياضي": "تقني رياضي",
  "رياضيات": "رياضيات",
  "الدروس التعليمية": "الدروس التعليمية",
  "المكتسبات القبلية": "المكتسبات القبلية",
  "التوزيع السنوي": "التوزيع السنوي",
  "محتوى مخصص للشعب العلمية - فيزياء وكيمياء": "محتوى مخصص للشعب العلمية - فيزياء وكيمياء",
  "محتوى مخصص للشعب الأدبية": "محتوى مخصص للشعب الأدبية",
  "محتوى مخصص لشعبة": "محتوى مخصص لشعبة",
  "الدروس التعليمية.desc": "جميع دروس الرابعة متوسط بالفيديو من قناة الأستاذ.",
  "المكتسبات القبلية.desc": "مراجعة الأساسيات قبل انطلاق برنامج شهادة التعليم المتوسط.",
  "التوزيع السنوي.desc": "التوزيع الرسمي لمادة العلوم الفيزيائية والتكنولوجيا (PDF).",

  // ---- ContentPage ----
  "cp.searchPh": "ابحث في",
  "cp.showing": "عرض",
  "cp.results": "نتيجة",
  "cp.empty": "لا توجد نتائج",
  "cp.emptyHint": "جرب كلمات بحث مختلفة",
  "cp.pdf": "تحميل PDF",

  // ---- Splash ----
  "splash.logoAlt": "شعار منصة الأستاذ بيكا للفيزياء",
  "splash.logoTitle": "منصة الأستاذ بيكا للفيزياء",
  "splash.welcome": "مرحبًا بك في منصة الأستاذ بيكا",
  "splash.subtitle": "لنبدأ رحلتك — اختر ما يناسبك للمتابعة",
  "splash.student": "أنا طالب",
  "splash.studentSub": "اختر مستواك الدراسي وابدأ فورًا",
  "splash.teacher": "أنا أستاذ / زائر",
  "splash.teacherSub": "الدخول إلى الصفحة الرئيسية",
  "splash.skip": "تخطي والدخول المباشر",
  "splash.chooseYear": "اختر مستواك الدراسي",
  "splash.back": "رجوع للخيارات",

  // ---- State views ----
  "sv.errorTitle": "تعذّر تحميل هذا القسم حاليًا",
  "sv.errorHint": "قد تكون هناك مشكلة مؤقتة في الشبكة. حاول مرة أخرى بعد قليل.",
  "sv.retry": "إعادة المحاولة",

  // ---- Tips ----
  "tips.label": "💡 نصيحة الأستاذ بيكا",
  "tips.close": "إغلاق النصيحة",

  // ---- Footer ----
  "footer.aboutText": "منصة الأستاذ بيكا للفيزياء - منصة تعليمية جزائرية تجمع كل ما يحتاجه الطالب في مكان واحد.",
  "footer.quickLinks": "روابط سريعة",
  "footer.contact": "تواصل معنا",
  "footer.sendMessage": "أرسل رسالة",
  "footer.linktree": "الرابط الشامل — كل المنصات",
  "footer.emailPh": "بريدك الإلكتروني",
  "footer.messagePh": "رسالتك...",
  "footer.send": "إرسال",
  "footer.sent": "✓ تم الإرسال بنجاح!",
  "footer.support": "دعم المحتوى ⚡",
  "footer.rights": "جميع الحقوق محفوظة",
  "footer.madeWith": "صُمِّم ب ❤️ للطالب الجزائري",

  // ---- Admin ----
  "admin.dashboard": "لوحة التحكم",
  "admin.resumes": "الملخصات",
  "admin.exercises": "التمارين",
  "admin.devoirs": "الفروض",
  "admin.videos": "الفيديوهات",
  "admin.courses": "الدورات",
  "admin.apps": "التطبيقات",
  "admin.announcements": "الإعلانات",
  "admin.subtitle": "لوحة التحكم",
  "admin.manage": "إدارة محتوى موقع منصة الأستاذ بيكا للفيزياء",
  "admin.add": "إضافة جديد",
  "admin.summaries": "ملخص",
  "admin.students": "طالب",
  "admin.views": "مشاهدة",
  "admin.satisfaction": "رضا الطلاب",
  "admin.thisMonth": "+5 هذا الشهر",
  "admin.thisWeek": "+120 هذا الأسبوع",
  "admin.today": "+1,200 اليوم",
  "admin.monthTrend": "↑ 2% هذا الشهر",
  "admin.recent": "آخر الإضافات",
  "admin.published": "منشور",
  "admin.draft": "مسودة",
  "admin.search": "ابحث...",
  "admin.title": "العنوان",
  "admin.level": "المستوى",
  "admin.subject": "المادة",
  "admin.date": "التاريخ",
  "admin.status": "الحالة",
  "admin.actions": "إجراءات",
  "admin.empty": "لا توجد عناصر",
  "admin.editItem": "تعديل العنصر",
  "admin.addItem": "إضافة عنصر جديد",
  "admin.titleLabel": "العنوان",
  "admin.titlePh": "عنوان المحتوى",
  "admin.subjectPh": "مثال: الميكانيكا",
  "admin.description": "الوصف",
  "admin.descriptionPh": "وصف المحتوى...",
  "admin.uploadPdf": "انقر لرفع ملف PDF",
  "admin.save": "حفظ",
  "admin.cancel": "إلغاء",
  "admin.role": "مشرف",
  "admin.sidebarId": "لوحة التحكم",

  // ---- Site data (content keys) ----
  "يوتيوب": "يوتيوب",
  "فيسبوك": "فيسبوك",
  "تلغرام": "تلغرام",
  "واتساب": "واتساب",
  "تيك توك": "تيك توك",
  "إنستغرام": "إنستغرام",
  "دروس مفصلة وشروحات كاملة بالفيديو": "دروس مفصلة وشروحات كاملة بالفيديو",
  "الصفحة الرسمية — منشورات ومستجدات يومية": "الصفحة الرسمية — منشورات ومستجدات يومية",
  "مجلد القنوات — كل الملفات و PDF": "مجلد القنوات — كل الملفات و PDF",
  "الملفات والتحديثات المباشرة": "الملفات والتحديثات المباشرة",
  "أفكار سريعة وفيديوهات قصيرة": "أفكار سريعة وفيديوهات قصيرة",
  "ملخصات يومية ونظام الكاروزول": "ملخصات يومية ونظام الكاروزول",
  "الصفحة الرسمية": "الصفحة الرسمية",
  "المحفظة الشاملة": "المحفظة الشاملة",
  "مجتمع الواتساب": "مجتمع الواتساب",
  "ماسنجر": "ماسنجر",
  "منتدى الأستاذ بيكا": "منتدى الأستاذ بيكا",
  "مجتمع الفيزياء": "مجتمع الفيزياء",
  "مجلد القنوات": "مجلد القنوات",
  "المنتدى المنظم — ملفات و نقاشات لكل المستويات": "المنتدى المنظم — ملفات و نقاشات لكل المستويات",
  "مجتمع الأستاذ بيكا للفيزياء على ماسنجر": "مجتمع الأستاذ بيكا للفيزياء على ماسنجر",
  "مجتمع الأستاذ بيكا للفيزياء على واتساب": "مجتمع الأستاذ بيكا للفيزياء على واتساب",
  "قسم البكالوريا (BAC)": "قسم البكالوريا (BAC)",
  "قسم الثانوي (1AS + 2AS)": "قسم الثانوي (1AS + 2AS)",
  "قسم شهادة التعليم المتوسط (BEM)": "قسم شهادة التعليم المتوسط (BEM)",
  "دردشة إنستغرام": "دردشة إنستغرام",
  "دردشة ماسنجر": "دردشة ماسنجر",
  "دردشة تيك توك": "دردشة تيك توك",
  "دردشة إنستغرام المشتركة": "دردشة إنستغرام المشتركة",
  "دردشة ماسنجر المشتركة": "دردشة ماسنجر المشتركة",
  "الجزائر": "الجزائر",

  // ---- Bookmarks ----
  "bookmarks.title": "المفضلة",
  "bookmarks.desc": "جميع المحتوى الذي حفظته للوصول السريع",
  "bookmarks.empty": "لا توجد عناصر في المفضلة",
  "bookmarks.emptyHint": "اضغط على أيقونة المرجعية على أي عنصر لإضافته هنا",
  "bookmarks.browse": "تصفح المحتوى",
  "bookmarks.searchPh": "ابحث في المفضلة...",
  "bookmarks.all": "الكل",
  "bookmarks.noResults": "لا توجد نتائج مطابقة",
  "bookmarks.count": "عنصر",

  // ---- Contact ----
  "contact.title": "اتصل بنا",
  "contact.desc": "نحب أن نسمع منك — أرسل لنا استفسارك أو اقتراحك وسنرد في أقرب وقت",
  "contact.info": "معلومات التواصل",
  "contact.email": "البريد الإلكتروني",
  "contact.phone": "الهاتف",
  "contact.location": "الموقع",
  "contact.responseTime": "وقت الرد",
  "contact.responseTimeVal": "خلال 24-48 ساعة",
  "contact.quickLinks": "روابط سريعة",
  "contact.sendMessage": "أرسل رسالة",
  "contact.name": "الاسم الكامل",
  "contact.namePh": "اسمك",
  "contact.emailPh": "example@email.com",
  "contact.subject": "الموضوع",
  "contact.subjectPh": "موضوع الرسالة",
  "contact.message": "الرسالة",
  "contact.messagePh": "اكتب رسالتك هنا...",
  "contact.send": "إرسال الرسالة",
  "contact.success": "تم الإرسال بنجاح!",
  "contact.successDesc": "شكرًا لتواصلك معنا. سنرد عليك في أقرب وقت ممكن.",

  // ---- FAQ ----
  "faq.title": "الأسئلة الشائعة",
  "faq.desc": "إجابات سريعة على أكثر الأسئلة تكرارًا — إذا لم تجد إجابتك، تواصل معنا",
  "faq.searchPh": "ابحث في الأسئلة...",
  "faq.noResults": "لا توجد نتائج لـ",
  "faq.notFound": "لم تجد إجابتك؟",
  "faq.notFoundDesc": "تواصل معنا مباشرة وسنساعدك",
  "faq.contactCta": "اتصل بنا",

  // ---- Stats ----
  "stats.title": "المنصة في أرقام",
  "stats.desc": "أرقام حقيقية تعكس ثقة آلاف الطلاب في محتوى المنصة",
  "stats.summaries": "ملخص وتمرين",
  "stats.students": "طالب مسجل",
  "stats.views": "مشاهدة",
  "stats.satisfaction": "نسبة الرضا",

  // ---- Notifications ----
  "notif.title": "تفعيل الإشعارات",
  "notif.desc": "اشترك لتصلك تنبيهات بالدروس الجديدة والملخصات المحدثة",
  "notif.enable": "تفعيل",
  "notif.later": "لاحقًا",
};

const fr: Record<string, string> = {
  home: "Accueil",
  "nav.years": "Niveaux",
  "nav.resources": "Ressources",
  "nav.search": "Rechercher...",
  "nav.searchPh": "Rechercher résumés, exercices, cours...",
  "nav.searchAria": "Recherche",
  "nav.soundOn": "Couper le son",
  "nav.soundOff": "Activer le son",
  "nav.soundEnabled": "Sons activés",
  "nav.soundMuted": "Sons coupés",
  "nav.themeDay": "Mode jour",
  "nav.themeNight": "Mode nuit",
  "nav.changeLang": "Changer de langue",
  "nav.menu": "Menu",
  "nav.quickSearch": "Recherche rapide ( / )",
  grade1: "1ère Année Secondaire",
  grade2: "2ème Année Secondaire",
  grade3: "3ème Année Secondaire",
  grade4: "4ème Année Moyenne",
  g1: "1AS",
  g2: "2AS",
  g3: "3AS",
  g4: "4AM",
  distributions: "Répartitions",
  videosNav: "Vidéos",
  teacherBag: "Sac de l'Enseignant",
  courses: "Cours",
  apps: "Applications",
  about: "À Propos",
  follow: "Suivez-Nous",
  admin: "Tableau de Bord",
  bookmarks: "Favoris",
  faq: "Questions Fréquentes",
  contact: "Contact",

  "common.all": "Tous",
  "common.view": "Voir",
  "common.download": "Télécharger",
  "common.back": "Retour",
  "common.explore": "Explorer",
  "common.loading": "Chargement...",
  "common.price": "DA",
  "common.free": "Gratuit",
  "common.locked": "Verrouillé",
  "common.freeCta": "Commencer gratuitement",
  "common.crumbHome": "Accueil",
  "common.new": "Nouveau",

  "hero.badge": "Notre slogan @profpica — apprends avec Pica",
  "hero.title1": "La plateforme de l'Enseignant Pica",
  "hero.title2": "pour la physique",
  "hero.title3": "tout ce dont l'élève a besoin",
  "hero.desc": "Résumés, exercices corrigés, examens, cours, applications intelligentes et dernières vidéos éducatives — tout en un seul endroit.",
  "hero.watch": "À Propos",
  "hero.courses": "Explorer les Cours",
  "hero.videoTitle": "Regarde les dernières leçons sur YouTube",
  "hero.videoSub": "@ProfPica — explications complètes et solutions d'exercices",
  "hero.videoTitleAttr": "Vidéo de présentation - DzPhy",
  "hero.posterAlt": "L'enseignant Pica - leçons de physique",
  "hero.watchAria": "Regarder les leçons sur la chaîne YouTube",

  "sh.title": "Commence ici",
  "sh.subtitle": "Cinq étapes simples pour découvrir tout ce dont tu as besoin",
  "sh.close": "Masquer le guide de démarrage",
  "sh.1title": "Choisis ta classe",
  "sh.1desc": "Commence à ton niveau",
  "sh.2title": "Regarde les leçons",
  "sh.2desc": "Vidéos et playlists organisées",
  "sh.3title": "Télécharge les fichiers",
  "sh.3desc": "Répartitions et résumés PDF",
  "sh.4title": "Suis les résumés",
  "sh.4desc": "Images et concepts rapides",
  "sh.5title": "Dernières actualités",
  "sh.5desc": "Nouvelles et annonces importantes",

  "gc.badge": "Niveaux scolaires",
  "gc.t1": "Choisis ton",
  "gc.t2": "niveau",
  "gc.desc": "Contenu organisé pour chaque niveau selon le programme algérien — chaque niveau a sa propre couleur",
  "gc.explore": "Explorer la section",
  "chip.resumes": "Résumés",
  "chip.exercises": "Exercices",
  "chip.devoirs": "Examens",
  "chip.tp": "TP",
  "chip.videos": "Vidéo",
  "chip.lessons": "Leçons",
  "chip.skills": "Prérequis",
  "chip.distribution": "Répartition",

  الميكانيكا: "Mécanique",
  الكهرباء: "Électricité",
  الكيمياء: "Chimie",
  البصريات: "Optique",
  النووي: "Nucléaire",
  الفيزياء: "Physique",
  "ميكانيكا/بصريات": "Mécanique/Optique",
  "جميع الوحدات": "Toutes les unités",

  "أسس الفيزياء والكيمياء — الميكانيكا، الكهرباء والمادة.": "Les bases de la physique-chimie — mécanique, électricité et matière.",
  "قوانين نيوتن، الطاقة، الدوائر الكهربائية والتفاعلات.": "Lois de Newton, énergie, circuits électriques et réactions.",
  "الإعداد للباكالوريا — الموجات، الميكانيكا والكيمياء المتقدمة.": "Préparation au BAC — ondes, mécanique et chimie avancée.",
  "التحضير لشهادة التعليم المتوسط — الوحدات، القياس والتحويلات.": "Préparation au BEM — unités, mesure et conversions.",
  "قوانين نيوتن": "Lois de Newton",
  "الطاقة": "Énergie",
  "الموجات": "Ondes",
  "الباكالوريا": "Baccalauréat",
  "المادة": "Matière",
  "القياس والتحويلات": "Mesure & conversions",
  "الوحدات": "Unités",

  "pg.badge": "Guide du nouvel élève",
  "pg.t1": "Que trouve-t-on sur",
  "pg.t2": "chaque plateforme ?",
  "pg.desc": "Chaque plateforme a un rôle bien précis — sache où aller et ce que tu y trouveras.",
  "pg.open": "Ouvrir la plateforme",
  "youtube.tagline": "Leçons détaillées",
  "youtube.desc": "Leçons complètes, directs, séries corrigées et révisions complètes pour chaque niveau.",
  "tiktok.tagline": "Idées rapides",
  "tiktok.desc": "Idées de physique rapides, concepts simplifiés ou astuces en quelques secondes.",
  "telegram.tagline": "Sac de fichiers",
  "telegram.desc": "Fichiers de l'enseignant : PDF, séries d'exercices, résumés et sujets téléchargeables.",
  "instagram.tagline": "Images & résumés",
  "instagram.desc": "Aides visuelles et résumés, lois et concepts essentiels pour mémoriser vite.",
  "facebook.tagline": "Actualités officielles",
  "facebook.desc": "Publications importantes, nouvelles ministérielles, alertes et résumés complets.",

  "vs.badge": "Vidéos éducatives",
  "vs.t1": "Apprends en vidéo",
  "vs.t2": "gratuitement",
  "vs.desc": "Leçons organisées en playlists par niveau — mises à jour automatiquement depuis YouTube.",
  "vs.all": "Toutes les vidéos",
  "vs.yt": "Playlists YouTube -",
  "vs.error": "Impossible de charger les vidéos, ouvre directement la page vidéos.",
  "vs.errorLink": "Aller aux playlists",
  "vs.videosCount": "vidéos",
  "vs.playlist": "Playlist",
  "vs.browseAll": "Parcourir toutes les playlists",
  "vs.tiktok": "Dernières vidéos TikTok -",
  "vs.tiktokMore": "Voir plus sur TikTok",
  "sg.tiktokTitle": "Meilleures vidéos TikTok",
  "sg.tiktokSub": "Idées rapides et clips choisis de @profpica",
  "sg.igTitle": "Dernières publications Instagram",
  "sg.igSub": "Derniers reels et publications de @prof_pica",

  "hs.badge": "Plateformes éducatives",
  "hs.t1": "Images, fichiers",
  "hs.t2": "et actualités",
  "hs.instagram": "Instagram — images & résumés",
  "hs.instagramSub": "Lois et concepts visuels rapides depuis @prof_pica",
  "hs.follow": "Suivre",
  "hs.telegram": "Telegram — sac de fichiers",
  "hs.telegramSub": "PDF, séries d'exercices, résumés et sujets",
  "hs.tg1": "Fichiers PDF prêts à télécharger",
  "hs.tg2": "Séries d'exercices et sujets",
  "hs.tg3": "Annonces et mises à jour importantes",
  "hs.tgCta": "Rejoindre les chaînes Telegram",
  "hs.facebook": "Facebook — actualités officielles",
  "hs.facebookSub": "Nouvelles ministérielles, alertes et résumés complets",
  "hs.fbOfficial": "Page officielle",
  "hs.fbOfficialSub": "Publications et actualités quotidiennes",
  "hs.fbPersonal": "Compte personnel de l'enseignant",
  "hs.fbPersonalSub": "Contact direct et échanges avec l'enseignant Pica",
  "hs.all": "Toutes les plateformes et communautés",

  "lc.badge": "Derniers ajouts",
  "lc.t1": "Dernières",
  "lc.t2": "publications",
  "lc.all": "Voir tout",
  "lc.watch": "Voir",
  "lc.pdf": "Télécharger PDF",
  "السنة الأولى": "1ère année",
  "السنة الثانية": "2ème année",
  "السنة الثالثة": "3ème année",
  "ملخص": "Résumé",
  "تمارين": "Exercices",
  "فرض": "Devoir",
  "عمل تطبيقي": "Travail pratique",
  "فيديو": "Vidéo",

  "cs.badge": "Cours",
  "cs.t1": "Cours",
  "cs.t2": "spécials",
  "cs.t3": "de physique",
  "cs.all": "Tous les cours",
  "cs.free": "Cours gratuits",
  "cs.paid": "Cours payants",
  "cs.watch": "Voir le cours",
  "cs.lessons": "leçons",
  "cs.modalTitle": "Contacter l'enseignant",
  "cs.modalDesc": "Pour plus d'informations et pour obtenir le lien d'accès au cours payant, contactez directement l'enseignant Pica.",
  "cs.modalCta": "Contacter l'enseignant",
  "cs.modalClose": "Fermer",

  "as.badge": "Applications",
  "as.t1": "Découvre les outils",
  "as.t2": "de la plateforme",
  "as.t3": "de l'enseignant Pica",
  "as.desc": "Applications intelligentes conçues pour aider l'élève algérien à comprendre la physique de façon interactive",
  "as.try": "Essayer l'application",
  "apps.heroTitle": "Applications",
  "apps.heroDesc": "Outils intelligents de la plateforme — simulateurs interactifs et calculatrices physiques",

  "wd.badge": "Pourquoi la plateforme de l'enseignant Pica ?",
  "wd.t1": "Ce qui rend la plateforme",
  "wd.t2": "de l'enseignant Pica",
  "wd.t3": "différente",
  "wd.desc": "Nous ne sommes pas un simple site éducatif — un écosystème complet pour apprendre la physique correctement",
  "wd1.title": "Contenu organisé",
  "wd1.desc": "Un contenu méthodique qui suit le programme algérien étape par étape",
  "wd2.title": "Programme 100% algérien",
  "wd2.desc": "Conçu pour l'élève algérien et conforme aux programmes officiels du Ministère",
  "wd3.title": "Explications simplifiées",
  "wd3.desc": "Un style simple qui rend les concepts de physique les plus difficiles clairs et compréhensibles",
  "wd4.title": "Mises à jour continues",
  "wd4.desc": "Du nouveau contenu ajouté en continu, au rythme des changements du programme",
  "wd5.title": "Outils intelligents",
  "wd5.desc": "Applications et simulations interactives qui rendent l'apprentissage amusant",
  "wd6.title": "Communauté éducative",
  "wd6.desc": "Une communauté d'élèves et d'enseignants qui partagent et s'entraident",

  "ab.badge": "✍️ L'enseignant Pica 🎓",
  "ab.t1": "Qui est",
  "ab.t2": "l'enseignant Pica ?",
  "ab.zoom": "Clique sur l'image pour l'agrandir et lire le CV clairement",
  "ab.edu": "Diplômé de l'École Normale Supérieure",
  "ab.tagline": "Je simplifie la physique de façon facile et amusante 💡",
  "ab.item1": "📝 Résumés organisés et complets",
  "ab.item2": "📚 Solutions d'exercices étape par étape",
  "ab.item3": "💡 Des idées que tu ne trouveras pas dans les livres",
  "ab.follow": "🔗👇 Suivez-nous via les liens",
  "ab.mission": "Notre mission",
  "ab.missionDesc": "Rendre l'apprentissage de la physique agréable et accessible à chaque élève algérien, en offrant les meilleurs contenus éducatifs et outils intelligents gratuits.",

  // ---- Newsletter ----
  "newsletter.title": "Restez informé",
  "newsletter.desc": "Abonnez-vous à notre newsletter pour recevoir les derniers cours, résumés et exercices directement dans votre boîte mail",
  "newsletter.placeholder": "Entrez votre adresse e-mail",
  "newsletter.subscribe": "S'abonner",
  "newsletter.success": "Abonné !",
  "newsletter.privacy": "Nous respectons votre vie privée - nous ne partagerons jamais votre e-mail",

  "ab.heroTitle": "À Propos",
  "ab.heroDesc": "Découvrez l'enseignant Pica et la plateforme de physique",
  "ab.cvAlt": "CV - L'enseignant Pica",

  "teacher.title": "Sac de l'Enseignant",
  "teacher.desc": "Ressources pédagogiques complètes pour les enseignants de physique",
  "teacher.r1title": "Plans de leçons",
  "teacher.r1desc": "Plans de leçons prêts selon le programme officiel algérien",
  "teacher.r2title": "Modèles de devoirs",
  "teacher.r2desc": "Modèles de devoirs prêts à modifier et imprimer",
  "teacher.r3title": "Tests d'évaluation",
  "teacher.r3desc": "Des tests variés pour évaluer le niveau des élèves",
  "teacher.telegram": "📱 Contactez l'enseignant via Telegram",
  "teacher.telegramDesc": "Rejoignez la chaîne Telegram pour les dernières mises à jour, fichiers et exercices",
  "teacher.join": "Rejoindre la chaîne",

  "dp.title": "Répartitions annuelles",
  "dp.desc": "Les répartitions officielles des sciences physiques pour tous les niveaux du secondaire et du BEM — téléchargez-les directement en PDF.",
  "dp.searchPh": "Rechercher une répartition, un niveau, une filière...",
  "dp.level": "Niveau",
  "dp.stream": "Filière",
  "dp.category": "Catégorie",
  "dp.showing": "Affichage de",
  "dp.files": "fichier(s)",
  "dp.empty": "Aucun fichier trouvé",
  "dp.emptyHint": "Essayez de modifier les filtres ou les mots de recherche",
  "dp.download": "Téléchargement direct (PDF)",
  "dp.soon": "Bientôt",

  "vp.badge": "Vidéos éducatives",
  "vp.title": "Playlists",
  "vp.desc": "Toutes les leçons et prérequis de sciences physiques organisés en playlists par niveau — le contenu se met à jour automatiquement à chaque nouvelle vidéo sur YouTube.",
  "vp.loading": "Récupération des dernières vidéos depuis YouTube...",
  "vp.errorTitle": "Impossible de contacter les playlists",
  "vp.errorHint": "Vérifiez votre connexion puis réessayez",
  "vp.emptyTitle": "Aucune playlist pour ce niveau pour l'instant",
  "vp.emptyHint": "Essayez un autre niveau ou parcourez toutes les playlists.",
  "vp.all": "Toutes les playlists",
  "vp.openFull": "Ouvrir la playlist complète sur YouTube",
  "vp.watchAll": "Voir toutes les vidéos de cette playlist sur YouTube",
  "أفكار ودورات": "Idées & cours",

  "sp.title": "Rechercher sur la plateforme de physique",
  "sp.desc": "Leçons, résumés, exercices, devoirs, vidéos, cours et répartitions — tout en un seul endroit",
  "sp.aria": "Rechercher sur la plateforme",
  "sp.placeholder": "Écris : Newton, électricité, projectiles, BAC...",
  "sp.empty": "Commence par écrire ce que tu cherches",
  "sp.emptySub": "Résumés, exercices, devoirs, vidéos, cours...",
  "sp.noResults": "Aucun résultat pour",
  "sp.noResultsHint": "Essaie un autre mot comme : Newton, électricité, BEM",
  "sp.for": "résultat(s) pour",
  "sp.kbd": "— utilisez ↑ ↓ puis Entrée",
  "مستوى دراسي": "Niveau scolaire",
  "دورة": "Cours",
  "توزيع سنوي": "Répartition annuelle",
  "تطبيق": "Application",
  "صفحة": "Page",
  "فيديوهات": "Vidéos",

  "fp.title": "Suivez-Nous",
  "fp.desc": "Toutes les plateformes de l'enseignant Pica au même endroit — restez informé des dernières leçons, fichiers et mises à jour.",
  "fp.linktree": "Lien global — linktr.ee/profpica",
  "fp.official": "Plateformes officielles",
  "fp.officialSub": "Les chaînes de suivi quotidien de l'enseignant Pica",
  "fp.communities": "Communautés organisées",
  "fp.communitiesSub": "Dossiers de chaînes et communautés de discussion — fichiers et esprit d'équipe",
  "fp.groups": "Groupes de discussion selon ton niveau",
  "fp.groupsSub": "Chats directs sur Instagram et Messenger selon la classe",
  "fp.support": "Soutien du contenu & paiement rapide ⚡",
  "fp.supportSub": "Contribuez à la continuité du contenu éducatif gratuit",
  "fp.copied": "Copié !",
  "fp.copy": "Copier",

  "gd.distBanner": "Répartition annuelle —",
  "gd.distDesc": "Téléchargez directement la répartition officielle des sciences physiques en PDF.",
  "gd.download": "Télécharger",
  "gd.chooseStream": "Choisis ta filière",
  "gd.chooseStreamSub": "Choisis ta filière pour accéder au contenu dédié",
  "gd.sciStreams": "Filières scientifiques",
  "gd.litStreams": "Filières littéraires",
  "gd.choose": "Choisir",
  "gd.back": "Retour aux filières",
  "gd.contentSci": "Contenu — filière scientifique",
  "gd.contentLit": "Contenu — filière littéraire",
  "gd.chooseSection": "Choisis la section à parcourir",
  "gd.bemTitle": "Contenu de l'examen du BEM",
  "gd.explore": "Explorer",
  "الشعب العلمية": "Filières scientifiques",
  "الشعب الأدبية": "Filières littéraires",
  "علوم تجريبية": "Sciences Exp",
  "تقني رياضي": "Tech Math",
  "رياضيات": "Mathématiques",
  "الدروس التعليمية": "Leçons",
  "المكتسبات القبلية": "Prérequis",
  "التوزيع السنوي": "Répartition annuelle",
  "محتوى مخصص للشعب العلمية - فيزياء وكيمياء": "Contenu dédié aux filières scientifiques — physique et chimie",
  "محتوى مخصص للشعب الأدبية": "Contenu dédié aux filières littéraires",
  "محتوى مخصص لشعبة": "Contenu dédié à la filière",
  "الدروس التعليمية.desc": "Toutes les leçons de 4ème année moyenne en vidéo depuis la chaîne de l'enseignant.",
  "المكتسبات القبلية.desc": "Révision des bases avant le programme de l'examen du BEM.",
  "التوزيع السنوي.desc": "La répartition officielle des sciences physiques et de la technologie (PDF).",

  "cp.searchPh": "Rechercher dans",
  "cp.showing": "Affichage de",
  "cp.results": "résultat(s)",
  "cp.empty": "Aucun résultat",
  "cp.emptyHint": "Essayez d'autres mots de recherche",
  "cp.pdf": "Télécharger PDF",

  "splash.logoAlt": "Logo de la plateforme de l'enseignant Pica",
  "splash.logoTitle": "La plateforme de l'enseignant Pica pour la physique",
  "splash.welcome": "Bienvenue sur la plateforme de l'enseignant Pica",
  "splash.subtitle": "Commençons l'aventure — choisis ce qui te convient",
  "splash.student": "Je suis élève",
  "splash.studentSub": "Choisis ton niveau et commence immédiatement",
  "splash.teacher": "Je suis enseignant / visiteur",
  "splash.teacherSub": "Accéder à la page d'accueil",
  "splash.skip": "Passer et entrer directement",
  "splash.chooseYear": "Choisis ton niveau scolaire",
  "splash.back": "Retour aux options",

  "sv.errorTitle": "Impossible de charger cette section pour l'instant",
  "sv.errorHint": "Il y a peut-être un problème temporaire de réseau. Réessayez plus tard.",
  "sv.retry": "Réessayer",

  "tips.label": "💡 Le conseil de l'enseignant Pica",
  "tips.close": "Fermer le conseil",

  "footer.aboutText": "La plateforme de l'enseignant Pica pour la physique — une plateforme éducative algérienne qui rassemble tout ce dont l'élève a besoin.",
  "footer.quickLinks": "Liens Rapides",
  "footer.contact": "Contactez-Nous",
  "footer.sendMessage": "Envoyer un Message",
  "footer.linktree": "Lien global — toutes les plateformes",
  "footer.emailPh": "Votre e-mail",
  "footer.messagePh": "Votre message...",
  "footer.send": "Envoyer",
  "footer.sent": "✓ Message envoyé avec succès !",
  "footer.support": "Soutien du contenu ⚡",
  "footer.rights": "Tous droits réservés",
  "footer.madeWith": "Conçu avec ❤️ pour l'élève algérien",

  "admin.dashboard": "Tableau de Bord",
  "admin.resumes": "Résumés",
  "admin.exercises": "Exercices",
  "admin.devoirs": "Examens",
  "admin.videos": "Vidéos",
  "admin.courses": "Cours",
  "admin.apps": "Applications",
  "admin.announcements": "Annonces",
  "admin.subtitle": "Tableau de Bord",
  "admin.manage": "Gérer le contenu de la plateforme",
  "admin.add": "Ajouter",
  "admin.summaries": "Résumés",
  "admin.students": "Élèves",
  "admin.views": "Vues",
  "admin.satisfaction": "Satisfaction",
  "admin.thisMonth": "+5 ce mois",
  "admin.thisWeek": "+120 cette semaine",
  "admin.today": "+1 200 aujourd'hui",
  "admin.monthTrend": "↑ 2% ce mois",
  "admin.recent": "Derniers ajouts",
  "admin.published": "Publié",
  "admin.draft": "Brouillon",
  "admin.search": "Rechercher...",
  "admin.title": "Titre",
  "admin.level": "Niveau",
  "admin.subject": "Matière",
  "admin.date": "Date",
  "admin.status": "Statut",
  "admin.actions": "Actions",
  "admin.empty": "Aucun élément",
  "admin.editItem": "Modifier l'élément",
  "admin.addItem": "Ajouter un nouvel élément",
  "admin.titleLabel": "Titre",
  "admin.titlePh": "Titre du contenu",
  "admin.subjectPh": "Exemple : Mécanique",
  "admin.description": "Description",
  "admin.descriptionPh": "Description du contenu...",
  "admin.uploadPdf": "Cliquer pour envoyer un fichier PDF",
  "admin.save": "Enregistrer",
  "admin.cancel": "Annuler",
  "admin.role": "Administrateur",
  "admin.sidebarId": "Tableau de Bord",

  "يوتيوب": "YouTube",
  "فيسبوك": "Facebook",
  "تلغرام": "Telegram",
  "واتساب": "WhatsApp",
  "تيك توك": "TikTok",
  "إنستغرام": "Instagram",
  "دروس مفصلة وشروحات كاملة بالفيديو": "Leçons détaillées et explications complètes en vidéo",
  "الصفحة الرسمية — منشورات ومستجدات يومية": "Page officielle — publications et actualités quotidiennes",
  "مجلد القنوات — كل الملفات و PDF": "Dossier de chaînes — tous les fichiers et PDF",
  "الملفات والتحديثات المباشرة": "Fichiers et mises à jour directes",
  "أفكار سريعة وفيديوهات قصيرة": "Idées rapides et vidéos courtes",
  "ملخصات يومية ونظام الكاروزول": "Résumés quotidiens et système carrousel",
  "الصفحة الرسمية": "Page officielle",
  "المحفظة الشاملة": "Sac complet",
  "مجتمع الواتساب": "Communauté WhatsApp",
  "ماسنجر": "Messenger",
  "منتدى الأستاذ بيكا": "Forum de l'enseignant Pica",
  "مجتمع الفيزياء": "Communauté de physique",
  "مجلد القنوات": "Dossier de chaînes",
  "المنتدى المنظم — ملفات و نقاشات لكل المستويات": "Forum organisé — fichiers et discussions pour tous les niveaux",
  "مجتمع الأستاذ بيكا للفيزياء على ماسنجر": "La communauté de physique de l'enseignant Pica sur Messenger",
  "مجتمع الأستاذ بيكا للفيزياء على واتساب": "La communauté de physique de l'enseignant Pica sur WhatsApp",
  "قسم البكالوريا (BAC)": "Classe du Baccalauréat (BAC)",
  "قسم الثانوي (1AS + 2AS)": "Classe du secondaire (1AS + 2AS)",
  "قسم شهادة التعليم المتوسط (BEM)": "Classe du BEM",
  "دردشة إنستغرام": "Chat Instagram",
  "دردشة ماسنجر": "Chat Messenger",
  "دردشة تيك توك": "Chat TikTok",
  "دردشة إنستغرام المشتركة": "Chat Instagram commun",
  "دردشة ماسنجر المشتركة": "Chat Messenger commun",
  "الجزائر": "Algérie",

  "bookmarks.title": "Favoris",
  "bookmarks.desc": "Tout le contenu que vous avez sauvegardé pour un accès rapide",
  "bookmarks.empty": "Aucun élément dans les favoris",
  "bookmarks.emptyHint": "Cliquez sur l'icône signet sur n'importe quel élément pour l'ajouter ici",
  "bookmarks.browse": "Parcourir le contenu",
  "bookmarks.searchPh": "Rechercher dans les favoris...",
  "bookmarks.all": "Tous",
  "bookmarks.noResults": "Aucun résultat correspondant",
  "bookmarks.count": "éléments",

  "contact.title": "Contactez-Nous",
  "contact.desc": "Nous aimons vous entendre — envoyez-nous votre question ou suggestion et nous répondrons rapidement",
  "contact.info": "Informations de contact",
  "contact.email": "E-mail",
  "contact.phone": "Téléphone",
  "contact.location": "Localisation",
  "contact.responseTime": "Temps de réponse",
  "contact.responseTimeVal": "Dans 24-48 heures",
  "contact.quickLinks": "Liens rapides",
  "contact.sendMessage": "Envoyer un message",
  "contact.name": "Nom complet",
  "contact.namePh": "Votre nom",
  "contact.emailPh": "example@email.com",
  "contact.subject": "Sujet",
  "contact.subjectPh": "Sujet du message",
  "contact.message": "Message",
  "contact.messagePh": "Écrivez votre message ici...",
  "contact.send": "Envoyer le message",
  "contact.success": "Envoyé avec succès !",
  "contact.successDesc": "Merci de nous avoir contactés. Nous vous répondrons dès que possible.",

  "faq.title": "Questions Fréquentes",
  "faq.desc": "Réponses rapides aux questions les plus fréquentes — si vous ne trouvez pas votre réponse, contactez-nous",
  "faq.searchPh": "Rechercher dans les questions...",
  "faq.noResults": "Aucun résultat pour",
  "faq.notFound": "Vous n'avez pas trouvé votre réponse ?",
  "faq.notFoundDesc": "Contactez-nous directement et nous vous aiderons",
  "faq.contactCta": "Contactez-nous",

  "stats.title": "La plateforme en chiffres",
  "stats.desc": "Des chiffres réels qui reflètent la confiance de milliers d'étudiants",
  "stats.summaries": "Résumés & Exercices",
  "stats.students": "Étudiants inscrits",
  "stats.views": "Vues",
  "stats.satisfaction": "Taux de satisfaction",

  "notif.title": "Activer les notifications",
  "notif.desc": "Abonnez-vous pour recevoir des alertes sur les nouvelles leçons et résumés",
  "notif.enable": "Activer",
  "notif.later": "Plus tard",
};

const en: Record<string, string> = {
  home: "Home",
  "nav.years": "Years",
  "nav.resources": "Resources",
  "nav.search": "Search...",
  "nav.searchPh": "Search summaries, exercises, lessons...",
  "nav.searchAria": "Search",
  "nav.soundOn": "Mute sounds",
  "nav.soundOff": "Enable sounds",
  "nav.soundEnabled": "Sounds on",
  "nav.soundMuted": "Sounds muted",
  "nav.themeDay": "Light mode",
  "nav.themeNight": "Dark mode",
  "nav.changeLang": "Change language",
  "nav.menu": "Menu",
  "nav.quickSearch": "Quick search ( / )",
  grade1: "1st Year Secondary",
  grade2: "2nd Year Secondary",
  grade3: "3rd Year Secondary",
  grade4: "4th Year Middle",
  g1: "1AS",
  g2: "2AS",
  g3: "3AS",
  g4: "4AM",
  distributions: "Distributions",
  videosNav: "Videos",
  teacherBag: "Teacher's Bag",
  courses: "Courses",
  apps: "Apps & Tools",
  about: "About Us",
  follow: "Follow Us",
  admin: "Dashboard",
  bookmarks: "Bookmarks",
  faq: "FAQ",
  contact: "Contact",

  "common.all": "All",
  "common.view": "View",
  "common.download": "Download",
  "common.back": "Back",
  "common.explore": "Explore",
  "common.loading": "Loading...",
  "common.price": "DZD",
  "common.free": "Free",
  "common.locked": "Locked",
  "common.freeCta": "Start free",
  "common.crumbHome": "Home",
  "common.new": "New",

  "hero.badge": "Our motto @profpica — learn with Pica",
  "hero.title1": "The Prof. Pica Platform",
  "hero.title2": "for Teaching Physics",
  "hero.title3": "Everything a Student Needs",
  "hero.desc": "Summaries, solved exercises, exams, courses, smart apps, and the latest educational videos — all in one place.",
  "hero.watch": "About Us",
  "hero.courses": "Explore Courses",
  "hero.videoTitle": "Watch the latest lessons on YouTube",
  "hero.videoSub": "@ProfPica — full explanations and exercise solutions",
  "hero.videoTitleAttr": "Intro video - DzPhy",
  "hero.posterAlt": "Prof. Pica - physics lessons",
  "hero.watchAria": "Watch lessons on the YouTube channel",

  "sh.title": "Start Here",
  "sh.subtitle": "Five simple steps to discover everything you need",
  "sh.close": "Hide the start guide",
  "sh.1title": "Pick your year",
  "sh.1desc": "Start at your grade level",
  "sh.2title": "Watch lessons",
  "sh.2desc": "Organized videos & playlists",
  "sh.3title": "Download files",
  "sh.3desc": "Distributions & PDF summaries",
  "sh.4title": "Follow summaries",
  "sh.4desc": "Images & quick concepts",
  "sh.5title": "Latest updates",
  "sh.5desc": "Important news & announcements",

  "gc.badge": "Grade Levels",
  "gc.t1": "Choose your",
  "gc.t2": "level",
  "gc.desc": "Organized content for every level following the Algerian curriculum — each level has its own color",
  "gc.explore": "Explore section",
  "chip.resumes": "Summaries",
  "chip.exercises": "Exercises",
  "chip.devoirs": "Tests",
  "chip.tp": "Practical",
  "chip.videos": "Video",
  "chip.lessons": "Lessons",
  "chip.skills": "Prereqs",
  "chip.distribution": "Distribution",

  الميكانيكا: "Mechanics",
  الكهرباء: "Electricity",
  الكيمياء: "Chemistry",
  البصريات: "Optics",
  النووي: "Nuclear",
  الفيزياء: "Physics",
  "ميكانيكا/بصريات": "Mechanics/Optics",
  "جميع الوحدات": "All units",

  "أسس الفيزياء والكيمياء — الميكانيكا، الكهرباء والمادة.": "Foundations of physics-chemistry — mechanics, electricity and matter.",
  "قوانين نيوتن، الطاقة، الدوائر الكهربائية والتفاعلات.": "Newton's laws, energy, electric circuits and reactions.",
  "الإعداد للباكالوريا — الموجات، الميكانيكا والكيمياء المتقدمة.": "BAC preparation — waves, mechanics and advanced chemistry.",
  "التحضير لشهادة التعليم المتوسط — الوحدات، القياس والتحويلات.": "BEM preparation — units, measurement and conversions.",
  "قوانين نيوتن": "Newton's laws",
  "الطاقة": "Energy",
  "الموجات": "Waves",
  "الباكالوريا": "Baccalaureate",
  "المادة": "Matter",
  "القياس والتحويلات": "Measurement & conversions",
  "الوحدات": "Units",

  "pg.badge": "New Student Guide",
  "pg.t1": "What will you find on",
  "pg.t2": "each platform?",
  "pg.desc": "Each platform has one clear purpose — know where to go and what you'll find everywhere.",
  "pg.open": "Open platform",
  "youtube.tagline": "Detailed lessons",
  "youtube.desc": "Full lessons, live streams, series solutions and complete reviews for every level.",
  "tiktok.tagline": "Quick ideas",
  "tiktok.desc": "Fast physics ideas, a concept simplified, or a smart trick in just seconds.",
  "telegram.tagline": "File bag",
  "telegram.desc": "Teacher files: PDF, exercise series, summaries and topics to download directly.",
  "instagram.tagline": "Images & summaries",
  "instagram.desc": "Visual summaries, laws and key concepts that stick fast.",
  "facebook.tagline": "Official updates",
  "facebook.desc": "Important posts, ministry news, official alerts and full summaries.",

  "vs.badge": "Educational Videos",
  "vs.t1": "Learn by video",
  "vs.t2": "for free",
  "vs.desc": "Lessons organized into playlists by level — updated automatically from YouTube.",
  "vs.all": "All videos",
  "vs.yt": "YouTube Playlists -",
  "vs.error": "Couldn't load videos, open the videos page directly instead.",
  "vs.errorLink": "Go to playlists",
  "vs.videosCount": "videos",
  "vs.playlist": "Playlist",
  "vs.browseAll": "Browse all playlists",
  "vs.tiktok": "Latest TikTok videos -",
  "vs.tiktokMore": "See more on TikTok",
  "sg.tiktokTitle": "Top TikTok videos",
  "sg.tiktokSub": "Quick ideas and selected clips from @profpica",
  "sg.igTitle": "Latest Instagram posts",
  "sg.igSub": "Latest reels and posts from @prof_pica",

  "hs.badge": "Educational Platforms",
  "hs.t1": "Images, files",
  "hs.t2": "and updates",
  "hs.instagram": "Instagram — images & summaries",
  "hs.instagramSub": "Quick visual laws and concepts from @prof_pica",
  "hs.follow": "Follow",
  "hs.telegram": "Telegram — file bag",
  "hs.telegramSub": "PDF, exercise series, summaries and topics",
  "hs.tg1": "PDF files ready to download",
  "hs.tg2": "Exercise series and topics",
  "hs.tg3": "Important announcements & updates",
  "hs.tgCta": "Join the Telegram channels",
  "hs.facebook": "Facebook — official updates",
  "hs.facebookSub": "Ministry news, alerts and full summaries",
  "hs.fbOfficial": "Official page",
  "hs.fbOfficialSub": "Daily posts and news & summaries",
  "hs.fbPersonal": "Teacher's personal account",
  "hs.fbPersonalSub": "Direct contact and interaction with Prof. Pica",
  "hs.all": "All platforms and communities",

  "lc.badge": "Latest Additions",
  "lc.t1": "What's newly",
  "lc.t2": "added",
  "lc.all": "View all",
  "lc.watch": "View",
  "lc.pdf": "Download PDF",
  "السنة الأولى": "Year 1",
  "السنة الثانية": "Year 2",
  "السنة الثالثة": "Year 3",
  "ملخص": "Summary",
  "تمارين": "Exercises",
  "فرض": "Test",
  "عمل تطبيقي": "Practical work",
  "فيديو": "Video",

  "cs.badge": "Educational Courses",
  "cs.t1": "Featured",
  "cs.t2": "physics",
  "cs.t3": "courses",
  "cs.all": "All courses",
  "cs.free": "Free courses",
  "cs.paid": "Paid courses",
  "cs.watch": "Watch course",
  "cs.lessons": "lessons",
  "cs.modalTitle": "Contact the teacher",
  "cs.modalDesc": "For more information and to get the access link to the paid course, please contact Prof. Pica directly.",
  "cs.modalCta": "Contact the teacher",
  "cs.modalClose": "Close",

  "as.badge": "Apps & Tools",
  "as.t1": "Discover Prof. Pica's",
  "as.t2": "Platform",
  "as.t3": "smart tools",
  "as.desc": "Smart apps designed to help Algerian students understand physics interactively",
  "as.try": "Try the app",
  "apps.heroTitle": "Apps & Tools",
  "apps.heroDesc": "Smart tools of Prof. Pica's platform — interactive simulators and physics calculators",

  "wd.badge": "Why Prof. Pica's Physics Platform?",
  "wd.t1": "What makes",
  "wd.t2": "Prof. Pica's Platform",
  "wd.t3": "different",
  "wd.desc": "We are not just an educational site — a complete system for learning physics the right way",
  "wd1.title": "Organized content",
  "wd1.desc": "Content arranged methodically, following the Algerian curriculum step by step",
  "wd2.title": "100% Algerian curriculum",
  "wd2.desc": "Designed for the Algerian student and aligned with the Ministry's official programs",
  "wd3.title": "Simplified explanations",
  "wd3.desc": "An easy, simple teaching style that makes the hardest physics concepts clear",
  "wd4.title": "Continuous updates",
  "wd4.desc": "New content added regularly, keeping pace with curriculum and exam changes",
  "wd5.title": "Smart tools",
  "wd5.desc": "Interactive apps and simulations that make learning physics fun and exciting",
  "wd6.title": "Learning community",
  "wd6.desc": "A community of students and teachers sharing knowledge and supporting each other",

  "ab.badge": "✍️ Prof. Pica 🎓",
  "ab.t1": "Who is",
  "ab.t2": "Prof. Pica?",
  "ab.zoom": "Click the image to zoom in and read the CV clearly",
  "ab.edu": "Graduate of the Higher Teacher Training School",
  "ab.tagline": "I simplify physics in an easy, fun way 💡",
  "ab.item1": "📝 Organized, comprehensive summaries",
  "ab.item2": "📚 Solved exercises, step by step",
  "ab.item3": "💡 Ideas you won't find in books",
  "ab.follow": "🔗👇 Follow us via the links",
  "ab.mission": "Our mission",
  "ab.missionDesc": "Making physics an enjoyable, accessible experience for every Algerian student by providing the best educational content and free smart tools.",

  // ---- Newsletter ----
  "newsletter.title": "Stay Updated",
  "newsletter.desc": "Subscribe to our newsletter to receive the latest lessons, summaries and exercises directly in your inbox",
  "newsletter.placeholder": "Enter your email address",
  "newsletter.subscribe": "Subscribe",
  "newsletter.success": "Subscribed!",
  "newsletter.privacy": "We respect your privacy - we will never share your email",

  "ab.heroTitle": "About Us",
  "ab.heroDesc": "Get to know Prof. Pica and the Prof. Pica physics platform",
  "ab.cvAlt": "Resume - Prof. Pica",

  "teacher.title": "Teacher's Bag",
  "teacher.desc": "Complete teaching resources for physics teachers",
  "teacher.r1title": "Lesson plans",
  "teacher.r1desc": "Ready lesson plans following the official Algerian curriculum",
  "teacher.r2title": "Test models",
  "teacher.r2desc": "Ready-to-edit, printable test models",
  "teacher.r3title": "Assessment tests",
  "teacher.r3desc": "Varied tests to assess students' levels",
  "teacher.telegram": "📱 Contact the teacher via Telegram",
  "teacher.telegramDesc": "Join the Telegram channel for the latest updates, files and exercises",
  "teacher.join": "Join the channel",

  "dp.title": "Annual Distributions",
  "dp.desc": "Official annual distributions of physical sciences for all secondary levels and the BEM exam — download them directly as PDF.",
  "dp.searchPh": "Search a distribution, level, stream...",
  "dp.level": "Level",
  "dp.stream": "Stream",
  "dp.category": "Category",
  "dp.showing": "Showing",
  "dp.files": "file(s)",
  "dp.empty": "No matching files",
  "dp.emptyHint": "Try adjusting the filters or search words",
  "dp.download": "Direct download (PDF)",
  "dp.soon": "Coming soon",

  "vp.badge": "Educational Videos",
  "vp.title": "Playlists",
  "vp.desc": "All lessons and prerequisites of physical sciences organized into playlists by level — content updates automatically whenever a new video is added on YouTube.",
  "vp.loading": "Fetching the latest videos from YouTube...",
  "vp.errorTitle": "Couldn't connect to playlists",
  "vp.errorHint": "Check your internet connection and try again",
  "vp.emptyTitle": "No playlists for this level yet",
  "vp.emptyHint": "Try another level or browse all playlists.",
  "vp.all": "All playlists",
  "vp.openFull": "Open the full playlist on YouTube",
  "vp.watchAll": "Watch all videos in this playlist on YouTube",
  "أفكار ودورات": "Ideas & courses",

  "sp.title": "Search Prof. Pica's Physics Platform",
  "sp.desc": "Lessons, summaries, exercises, tests, videos, courses and distributions — all in one place",
  "sp.aria": "Search the platform",
  "sp.placeholder": "Type: Newton, electricity, projectiles, BAC...",
  "sp.empty": "Start typing what you're looking for",
  "sp.emptySub": "Summaries, exercises, tests, videos, courses...",
  "sp.noResults": "No results for",
  "sp.noResultsHint": "Try another word like: Newton, electricity, BEM",
  "sp.for": "result(s) for",
  "sp.kbd": "-- use ↑ ↓ then Enter",
  "مستوى دراسي": "Grade level",
  "دورة": "Course",
  "توزيع سنوي": "Annual distribution",
  "تطبيق": "App",
  "صفحة": "Page",
  "فيديوهات": "Videos",

  "fp.title": "Follow Us",
  "fp.desc": "All of Prof. Pica's platforms in one place — stay up to date with the latest lessons, files and daily updates.",
  "fp.linktree": "Global link — linktr.ee/profpica",
  "fp.official": "Official platforms",
  "fp.officialSub": "Prof. Pica's daily follow channels",
  "fp.communities": "Organized communities",
  "fp.communitiesSub": "Channel folders and discussion communities — files and a team spirit",
  "fp.groups": "Chat groups by your level",
  "fp.groupsSub": "Direct chats on Instagram and Messenger by grade level",
  "fp.support": "Content support & quick payment ⚡",
  "fp.supportSub": "Contribute to the continuity of free educational content",
  "fp.copied": "Copied!",
  "fp.copy": "Copy",

  "gd.distBanner": "Annual distribution —",
  "gd.distDesc": "Download the official annual distribution of physical sciences as PDF directly.",
  "gd.download": "Download",
  "gd.chooseStream": "Choose your stream",
  "gd.chooseStreamSub": "Choose your stream to access dedicated content",
  "gd.sciStreams": "Scientific streams",
  "gd.litStreams": "Literary streams",
  "gd.choose": "Choose",
  "gd.back": "Back to streams",
  "gd.contentSci": "Study content — scientific stream",
  "gd.contentLit": "Study content — literary stream",
  "gd.chooseSection": "Choose the section you want to browse",
  "gd.bemTitle": "BEM exam content",
  "gd.explore": "Explore",
  "الشعب العلمية": "Scientific streams",
  "الشعب الأدبية": "Literary streams",
  "علوم تجريبية": "Experimental Sciences",
  "تقني رياضي": "Technical Math",
  "رياضيات": "Mathematics",
  "الدروس التعليمية": "Lessons",
  "المكتسبات القبلية": "Prerequisites",
  "التوزيع السنوي": "Annual distribution",
  "محتوى مخصص للشعب العلمية - فيزياء وكيمياء": "Content dedicated to scientific streams — physics and chemistry",
  "محتوى مخصص للشعب الأدبية": "Content dedicated to literary streams",
  "محتوى مخصص لشعبة": "Content dedicated to the",
  "الدروس التعليمية.desc": "All Grade 4 middle school lessons on video from the teacher's channel.",
  "المكتسبات القبلية.desc": "Review the basics before the BEM program starts.",
  "التوزيع السنوي.desc": "The official distribution for physics & technology (PDF).",

  "cp.searchPh": "Search in",
  "cp.showing": "Showing",
  "cp.results": "result(s)",
  "cp.empty": "No results",
  "cp.emptyHint": "Try different search words",
  "cp.pdf": "Download PDF",

  "splash.logoAlt": "Prof. Pica Physics Platform logo",
  "splash.logoTitle": "Prof. Pica's Physics Platform",
  "splash.welcome": "Welcome to Prof. Pica's Platform",
  "splash.subtitle": "Let's start your journey — choose what suits you",
  "splash.student": "I'm a student",
  "splash.studentSub": "Choose your grade level and start right away",
  "splash.teacher": "I'm a teacher / guest",
  "splash.teacherSub": "Go to the homepage",
  "splash.skip": "Skip and enter directly",
  "splash.chooseYear": "Choose your grade level",
  "splash.back": "Back to options",

  "sv.errorTitle": "Couldn't load this section right now",
  "sv.errorHint": "There may be a temporary network issue. Try again shortly.",
  "sv.retry": "Retry",

  "tips.label": "💡 Prof. Pica's tip",
  "tips.close": "Close the tip",

  "footer.aboutText": "Prof. Pica's Physics Platform — an Algerian educational platform bringing together everything a student needs in one place.",
  "footer.quickLinks": "Quick Links",
  "footer.contact": "Contact Us",
  "footer.sendMessage": "Send a Message",
  "footer.linktree": "Global link — all platforms",
  "footer.emailPh": "Your email",
  "footer.messagePh": "Your message...",
  "footer.send": "Send",
  "footer.sent": "✓ Message sent successfully!",
  "footer.support": "Content support ⚡",
  "footer.rights": "All Rights Reserved",
  "footer.madeWith": "Made with ❤️ for the Algerian Student",

  "admin.dashboard": "Dashboard",
  "admin.resumes": "Summaries",
  "admin.exercises": "Exercises",
  "admin.devoirs": "Exams",
  "admin.videos": "Videos",
  "admin.courses": "Courses",
  "admin.apps": "Apps",
  "admin.announcements": "Announcements",
  "admin.subtitle": "Dashboard",
  "admin.manage": "Manage content of Prof. Pica's physics platform",
  "admin.add": "Add new",
  "admin.summaries": "Summaries",
  "admin.students": "Students",
  "admin.views": "Views",
  "admin.satisfaction": "Satisfied",
  "admin.thisMonth": "+5 this month",
  "admin.thisWeek": "+120 this week",
  "admin.today": "+1,200 today",
  "admin.monthTrend": "↑ 2% this month",
  "admin.recent": "Recent additions",
  "admin.published": "Published",
  "admin.draft": "Draft",
  "admin.search": "Search...",
  "admin.title": "Title",
  "admin.level": "Level",
  "admin.subject": "Subject",
  "admin.date": "Date",
  "admin.status": "Status",
  "admin.actions": "Actions",
  "admin.empty": "No items",
  "admin.editItem": "Edit item",
  "admin.addItem": "Add new item",
  "admin.titleLabel": "Title",
  "admin.titlePh": "Content title",
  "admin.subjectPh": "Example: Mechanics",
  "admin.description": "Description",
  "admin.descriptionPh": "Content description...",
  "admin.uploadPdf": "Click to upload a PDF file",
  "admin.save": "Save",
  "admin.cancel": "Cancel",
  "admin.role": "Administrator",
  "admin.sidebarId": "Dashboard",

  "يوتيوب": "YouTube",
  "فيسبوك": "Facebook",
  "تلغرام": "Telegram",
  "واتساب": "WhatsApp",
  "تيك توك": "TikTok",
  "إنستغرام": "Instagram",
  "دروس مفصلة وشروحات كاملة بالفيديو": "Detailed lessons and full video explanations",
  "الصفحة الرسمية — منشورات ومستجدات يومية": "Official page — daily posts and updates",
  "مجلد القنوات — كل الملفات و PDF": "Channel folder — all files and PDFs",
  "الملفات والتحديثات المباشرة": "Direct files and updates",
  "أفكار سريعة وفيديوهات قصيرة": "Quick ideas and short videos",
  "ملخصات يومية ونظام الكاروزول": "Daily summaries and carousel system",
  "الصفحة الرسمية": "Official page",
  "المحفظة الشاملة": "Full pouch",
  "مجتمع الواتساب": "WhatsApp community",
  "ماسنجر": "Messenger",
  "منتدى الأستاذ بيكا": "Prof. Pica's forum",
  "مجتمع الفيزياء": "Physics community",
  "مجلد القنوات": "Channel folder",
  "المنتدى المنظم — ملفات و نقاشات لكل المستويات": "Organized forum — files and discussions for all levels",
  "مجتمع الأستاذ بيكا للفيزياء على ماسنجر": "Prof. Pica's physics community on Messenger",
  "مجتمع الأستاذ بيكا للفيزياء على واتساب": "Prof. Pica's physics community on WhatsApp",
  "قسم البكالوريا (BAC)": "Baccalaureate class (BAC)",
  "قسم الثانوي (1AS + 2AS)": "Secondary class (1AS + 2AS)",
  "قسم شهادة التعليم المتوسط (BEM)": "BEM class",
  "دردشة إنستغرام": "Instagram chat",
  "دردشة ماسنجر": "Messenger chat",
  "دردشة تيك توك": "TikTok chat",
  "دردشة إنستغرام المشتركة": "Shared Instagram chat",
  "دردشة ماسنجر المشتركة": "Shared Messenger chat",
  "الجزائر": "Algeria",

  "bookmarks.title": "Bookmarks",
  "bookmarks.desc": "All the content you've saved for quick access",
  "bookmarks.empty": "No items in bookmarks",
  "bookmarks.emptyHint": "Click the bookmark icon on any item to add it here",
  "bookmarks.browse": "Browse content",
  "bookmarks.searchPh": "Search in bookmarks...",
  "bookmarks.all": "All",
  "bookmarks.noResults": "No matching results",
  "bookmarks.count": "items",

  "contact.title": "Contact Us",
  "contact.desc": "We'd love to hear from you — send us your question or suggestion and we'll respond soon",
  "contact.info": "Contact Information",
  "contact.email": "Email",
  "contact.phone": "Phone",
  "contact.location": "Location",
  "contact.responseTime": "Response Time",
  "contact.responseTimeVal": "Within 24-48 hours",
  "contact.quickLinks": "Quick Links",
  "contact.sendMessage": "Send a Message",
  "contact.name": "Full Name",
  "contact.namePh": "Your name",
  "contact.emailPh": "example@email.com",
  "contact.subject": "Subject",
  "contact.subjectPh": "Message subject",
  "contact.message": "Message",
  "contact.messagePh": "Write your message here...",
  "contact.send": "Send Message",
  "contact.success": "Sent successfully!",
  "contact.successDesc": "Thank you for contacting us. We'll respond as soon as possible.",

  "faq.title": "Frequently Asked Questions",
  "faq.desc": "Quick answers to the most common questions — if you don't find your answer, contact us",
  "faq.searchPh": "Search in questions...",
  "faq.noResults": "No results for",
  "faq.notFound": "Didn't find your answer?",
  "faq.notFoundDesc": "Contact us directly and we'll help you",
  "faq.contactCta": "Contact Us",

  "stats.title": "The Platform in Numbers",
  "stats.desc": "Real numbers reflecting the trust of thousands of students",
  "stats.summaries": "Summaries & Exercises",
  "stats.students": "Registered Students",
  "stats.views": "Views",
  "stats.satisfaction": "Satisfaction Rate",

  "notif.title": "Enable Notifications",
  "notif.desc": "Subscribe to receive alerts for new lessons and updated summaries",
  "notif.enable": "Enable",
  "notif.later": "Later",
};

const translations: Record<Lang, Record<string, string>> = { ar, fr, en };

function readCookie(name: string): string | null {
  if (typeof document === "undefined") return null;
  const m = document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`));
  return m ? decodeURIComponent(m[1]) : null;
}

function initialLang(): Lang {
  if (typeof window === "undefined") return "ar";
  const c = readCookie(LANG_COOKIE);
  if (c && LANG_OPTIONS.includes(c as Lang)) return c as Lang;
  const stored = localStorage.getItem(LANG_COOKIE);
  if (stored && LANG_OPTIONS.includes(stored as Lang)) return stored as Lang;
  return "ar";
}

function writeLang(l: Lang) {
  try {
    document.cookie = `${LANG_COOKIE}=${l};path=/;max-age=31536000;samesite=lax`;
    localStorage.setItem(LANG_COOKIE, l);
  } catch {
    /* ignore */
  }
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ar",
  setLang: () => {},
  t: (k) => k,
  dir: "rtl",
});

export function LanguageProvider({
  children,
  initialLang: initial = undefined,
}: {
  children: ReactNode;
  initialLang?: Lang;
}) {
  const [lang, setLang] = useState<Lang>(() => initial ?? initialLang());

  useEffect(() => {
    document.documentElement.lang = lang === "ar" ? "ar" : lang;
    document.documentElement.dir = dirForLang(lang);
    writeLang(lang);
  }, [lang]);

  useEffect(() => {
    const onStorage = (e: StorageEvent) => {
      if (e.key === LANG_COOKIE && e.newValue && LANG_OPTIONS.includes(e.newValue as Lang)) {
        setLang(e.newValue as Lang);
      }
    };
    window.addEventListener("storage", onStorage);
    return () => window.removeEventListener("storage", onStorage);
  }, []);

  const changeLang = (l: Lang) => {
    setLang(l);
  };

  const t = (key: string) => translations[lang]?.[key] ?? translations.ar[key] ?? key;

  return (
    <LanguageContext.Provider
      value={{ lang, setLang: changeLang, t, dir: dirForLang(lang) }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}